# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(160, 500, 231, 31))
        self.startButton.setObjectName("startButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 171, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.timeChet = QtWidgets.QLineEdit(self.centralwidget)
        self.timeChet.setGeometry(QtCore.QRect(460, 0, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.timeChet.setFont(font)
        self.timeChet.setReadOnly(True)
        self.timeChet.setObjectName("timeChet")
        self.timerBar = QtWidgets.QProgressBar(self.centralwidget)
        self.timerBar.setGeometry(QtCore.QRect(0, 0, 351, 41))
        self.timerBar.setMaximum(429)
        self.timerBar.setProperty("value", 0)
        self.timerBar.setTextVisible(False)
        self.timerBar.setObjectName("timerBar")
        self.audioLabel = QtWidgets.QLabel(self.centralwidget)
        self.audioLabel.setGeometry(QtCore.QRect(10, 50, 531, 131))
        self.audioLabel.setObjectName("audioLabel")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(0, 270, 531, 151))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtWidgets.QSplitter(self.splitter_6)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 210, 111, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Готово"))
        self.label_2.setText(_translate("MainWindow", "Времени осталось:"))
        self.timeChet.setText(_translate("MainWindow", "0"))
        self.audioLabel.setText(_translate("MainWindow", "Перед Вами 5 предложений A — E с пропусками и варианты слов или словосочетаний\n"
" для заполнения этих пропусков, обозначенные цифрами 1 — 3. Внимательно прочитайте их.\n"
"Вы услышите диалог. Для каждого предложения A — E выберите\n"
" слово или словосочетание, соответствующее содержанию диалога.\n"
" К каждому пропуску подходит только одно слово или словосочетание. Вы услышите запись дважды. При повторном прослушивании проверьте себя.\n"
" У Вас есть 45 секунд, чтобы ознакомиться с предложениями."))
        self.lineEdit.setText(_translate("MainWindow", "Mark\'s project has good________"))
        self.lineEdit_6.setText(_translate("MainWindow", "pictures;examples;facts"))
        self.lineEdit_2.setText(_translate("MainWindow", "Mark\'s class will go to the Museum of _________"))
        self.lineEdit_7.setText(_translate("MainWindow", "sport;history;science"))
        self.lineEdit_3.setText(_translate("MainWindow", "The lessons finish at _________ on Friday"))
        self.lineEdit_8.setText(_translate("MainWindow", "2:20pm;2pm;2:30pm"))
        self.lineEdit_4.setText(_translate("MainWindow", "Mark\'s class is meeting _________"))
        self.lineEdit_9.setText(_translate("MainWindow", "by the information board;opposite the entrance;next to the library"))
        self.lineEdit_5.setText(_translate("MainWindow", "The ticket to the Museum costs _________."))
        self.lineEdit_10.setText(_translate("MainWindow", "£8;£5;£8"))
        self.label.setText(_translate("MainWindow", "Загрузить аудио"))
