# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reading.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.microphoneButton = QtWidgets.QPushButton(self.centralwidget)
        self.microphoneButton.setEnabled(False)
        self.microphoneButton.setGeometry(QtCore.QRect(150, 260, 241, 241))
        self.microphoneButton.setAutoFillBackground(False)
        self.microphoneButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("voice-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.microphoneButton.setIcon(icon)
        self.microphoneButton.setIconSize(QtCore.QSize(228, 300))
        self.microphoneButton.setCheckable(False)
        self.microphoneButton.setFlat(True)
        self.microphoneButton.setObjectName("microphoneButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(160, 500, 231, 31))
        self.startButton.setObjectName("startButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 171, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.timeChet = QtWidgets.QLineEdit(self.centralwidget)
        self.timeChet.setGeometry(QtCore.QRect(460, 0, 113, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.timeChet.setFont(font)
        self.timeChet.setReadOnly(True)
        self.timeChet.setObjectName("timeChet")
        self.timerBar = QtWidgets.QProgressBar(self.centralwidget)
        self.timerBar.setGeometry(QtCore.QRect(0, 0, 351, 61))
        self.timerBar.setMaximum(429)
        self.timerBar.setProperty("value", 0)
        self.timerBar.setTextVisible(False)
        self.timerBar.setObjectName("timerBar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 70, 531, 31))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 531, 151))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Готово"))
        self.label_2.setText(_translate("MainWindow", "Времени осталось:"))
        self.timeChet.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Прочитайте текст вслух.\n"
" У вас есть полторы минуты на подготовку и полторы минуты, чтобы прочитать текст вслух."))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">People like songs. We can listen to songs or sing songs. There are different kinds of songs, and so there is a song for any mood or occasion. Classical songs have traditional tunes. Folk songs reflect the culture of a country. Pop songs are modern. Mostly young people like to listen to them or dance to them. Rock songs are also very popular with teenagers. They like rock concerts very much. Country songs are easy to listen to. They put you in a good mood and you feel like dancing and singing along. So people can choose what they like.</p></body></html>"))
